# http://module-build.sourceforge.net/META-spec.html
name:         FTN-Nodelist
version:      1.02
version_from: Nodelist.pm
license:      perl
installdirs:  site
requires:
    FTN::Address:                  1.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
