--- #YAML:1.0
name:                FTN-Nodelist
version:             1.06
abstract:            Process FTN Nodelist
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    FTN::Address:                  1.01
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Serguei Trouchelle <stro@railways.dp.ua>
